### ISSUE TITLE
测速失效

### ISSUE THREAD

**Issue by newton-miku** [ztelliot/taierspeed-cli#1]
大佬，最近测速使用发现好像只能获取到服务器，但是会提示服务器无响应
相应运行输出如下
Retrieving server list
ISP:            成都电信
Server:         成都电信 [125.69.87.194] (id = 1801)
Selected server 成都电信 (1801) is not responding at the moment, try again later

**Comment by ztelliot** [comment]
您好，最近 全球网测 服务器似乎都在维护，手机 app 也无法测速，这个我也没办法。您可以使用 -N 参数禁用这些服务器，仅使用来自 泰尔网测 的服务器测速。

**Comment by newton-miku** [comment]
了解了，我看仓库名字我以为只用了泰尔网测的服务器
