### ISSUE TITLE
Seems the tool is blokced by testing server

### ISSUE THREAD

**Issue by WFANG12719** [ztelliot/taierspeed-cli#2]
# ./taierspeed-cli_1.7.0_linux_armv7 -l
Error when fetching server list: 403 Forbidden
Terminated due to error

# ./taierspeed-cli_1.7.0_linux_armv7 -s 1 -q
Retrieving server list
Error when fetching server list: 403 Forbidden
Terminated due to error

Is it blocked by officical server？

**Comment by ztelliot** [comment]
Hello, to prevent abuse, frequently requested IP will be banned.
