### ISSUE TITLE
使用 >或tee重定向输出时候失败

### ISSUE THREAD

**Issue by YangHaoNing-CN** [ztelliot/taierspeed-cli#5]
![image](https://github.com/user-attachments/assets/c64e7e35-122c-41d9-890f-7ba742cc2666)

**Comment by ztelliot** [comment]
使用 `-q` 参数避免动态输出，`>` 及 `tee` 可以正常重定向

**Comment by YangHaoNing-CN** [comment]
坏，刚写完脚本过滤

**Comment by ztelliot** [comment]
您也可以使用 `--json` 参数直接获取原始结果

**Comment by YangHaoNing-CN** [comment]
建议将这些选项放到--help里？

**Comment by YangHaoNing-CN** [comment]
谢谢啦，没仔细看help
