### ISSUE TITLE
测试出现403 Forbidden可能是UA问题

### ISSUE THREAD

**Issue by rammiah** [ztelliot/taierspeed-cli#6]
我在自己的linux机器上测速的时候会报错403，但是windows机器上是能正常使用的，手动将ApiUA的GOOS替换成windows后，在linux上就能测速了, macos也会报403的错误，替换UA的OS为windows同样有用

**Comment by YangHaoNing-CN** [comment]
暂时没出现过403问题

**Comment by ztelliot** [comment]
API 并不会检查 UA 中的 GOOS 值

**Comment by rammiah** [comment]
> API 并不会检查 UA 中的 GOOS 值

现在的限流逻辑是什么？经常linux不能用，windows能用，都是一个局域网下的

**Comment by ztelliot** [comment]
单个 IP 在 1 小时内请求超过 50 次才会触发限流

**Comment by rammiah** [comment]
好的，谢谢解答
